services:
  homepage:
    build: .
    image: homepage:0.1
    container_name: homepage
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.homepage.rule=Host(`home.fiwservers.lol`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls.certresolver=porkbun
      - traefik.http.services.homepage.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
